databases:
  - name: task_manager_db
    plan: free
    databaseName: task_manager_db
    user: task_manager_db_user

services:
  - type: web
    plan: free
    name: task_manager
    runtime: python
    buildCommand: "make build"
    startCommand: "make start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task_manager_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4